In [15]:
import tensorflow as tf

In [16]:
tf.__version__

'1.0.1'

# 상수 만드는 방법 4가지 (변수도 마찬가지)
1. 직접 할당하기
    * tf.constant(값)
2. 특정값으로 할당하기
    * tf.zeros, tf.ones, tf.fill, tf.zeros_like, tf.ones_like
3. Sequential하게 할당하기
    * tf.linspace, tf.range
4. 랜덤하게 할당하기
    * tf.random_normal, tf.truncated_normal 등

### 1. 직접 할당하기

tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)

* 디폴트 이름이 Const이며, 내부적으로 Const, Const_1, Const_2... 식으로 자동 변환
* verify_shape은 디폴트로 False인데 이 경우 value와 shape이 다른 경우에 shape에 맞춰 준다. True이면 value와 shape이 다른 경우 에러 발생한다.

의도적으로 value와 shape을 모순되게 주고, verify_shape=True로 해 보겠습니다. 

In [19]:
# a = tf.constant(value=2, shape=[2,2], verify_shape=True)
# 에러 발생 - TypeError: Expected Tensor's shape: (2, 2), got ().

이번에는 value와 shape을 모순되게 주되, 디폴트 그대로 이용함으로써 verify_shape=False로 해 보겠습니다. 

In [22]:
b = tf.constant(value=2, shape=[2,2])
tf.InteractiveSession()
b.eval() # value와 shape이 모순되지만 shape을 따르게 된다.

array([[2, 2],
       [2, 2]], dtype=int32)

이번에도 value와 shape을 모순되게 주되, verify_shape=False인 경우인 다른 예입니다. 

In [23]:
c = tf.constant([2,1], shape=[3,3])
c.eval()

array([[2, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

다른 예를 보겠습니다.

* 브로드캐스팅이 발생하며
* element-wise 연산입니다.

In [26]:
a = tf.constant([2,2], name="a")
b = tf.constant([[0,1], [2,3]], name="b")
x = tf.add(a, b, name="add")
y = tf.multiply(a, b, name="multiply") # TF 1.0 부터는 mul() -> multiply()
with tf.Session() as sess:
    x, y = sess.run([x, y])
    print x
    print y

[[2 3]
 [4 5]]
[[0 2]
 [4 6]]


### 2. 특정값으로 할당하기

tf.zeros는 모든 원소를 0으로 할당해 준다. 

In [27]:
a = tf.zeros(shape=[2,3], dtype=tf.int32)
a

<tf.Tensor 'zeros:0' shape=(2, 3) dtype=int32>

In [28]:
tf.InteractiveSession()
a.eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

tf.zeros_like는 input_tensor로부터 shape과 dtype을 가져오되, 값을 모두 0으로 채워준다.

In [29]:
input_tensor = [[0,1], [2,3], [4,5]]

In [30]:
a = tf.zeros_like(input_tensor)
a

<tf.Tensor 'zeros_like:0' shape=(3, 2) dtype=int32>

In [31]:
a.eval()

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

dtype을 명시해 주면 해당 dtype으로 변경 가능하다. 단 shape은 무조건 계승한다.

In [32]:
b = tf.zeros_like(input_tensor, dtype=tf.float32)
b

<tf.Tensor 'zeros_like_1:0' shape=(3, 2) dtype=float32>

In [33]:
b.eval()

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]], dtype=float32)

tf.ones 와 tf.ones_like 도 동일한 형식으로 사용된다.

0,1 이외의 값을 주고 싶은 경우에는 tf.fill 을 활용한다. 차원과 값을 지정해 줄 수 있다. 값은 반드시 scalar이어야 한다.

In [34]:
c = tf.fill([3,3],7)
c

<tf.Tensor 'Fill:0' shape=(3, 3) dtype=int32>

In [35]:
c.eval()

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int32)

참고로 numpy에서 이처럼 0,1 이외의 값으로 채워주는 작업은 2단계로 진행해야 한다. 
* 1) numpy array c를 생성
* 2) c.fill(value) 

tf에서는 이를 한 단계로 간소화한 것이다.

### 3. Sequential하게 생성하기

numpy에도 있는 tf.linspace 사용 가능합니다. 단 tf.linspace에서는 시작값과 종료값이 반드시 float32 또는 float64 이어야만 합니다.

In [37]:
a = tf.linspace(10.0, 13.0, 4)
a.eval()

array([ 10.,  11.,  12.,  13.], dtype=float32)

In [39]:
# b = tf.linspace(1,12,3) # error

tf.range에서는 정수 사용이 가능합니다.

In [40]:
b = tf.range(1,10,3)
b.eval()

array([1, 4, 7], dtype=int32)

시작값과 종료값이 없으면 0부터 시작합니다.

In [41]:
c = tf.range(10)
c.eval()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

참고로 tensor object는 python, numpy와는 달리 순환문에 쓰일 수 없습니다.

In [42]:
# python 
for i in range(4):
    print i
0
1
2
3

0
1
2
3


3

In [43]:
# numpy
import numpy as np
for i in np.arange(4):
    print i

0
1
2
3


In [ ]:
# tf
# for i in tf.range(4): # error : 'Tensor' object is not iterable
#     print i

### 4. 랜덤하게 할당하기

tf.random_normal()은 주어진 평균과 표준편차에 기반하여 가우시안 정규분포를 따르는 값들로 생덤하게 생성해 준다.

In [44]:
a = tf.random_normal(shape=[10,3], mean=0, stddev=1.0, dtype=tf.float32)
a.eval() # outlier (-2 미만, 2 초과) 값이 존재한다. 

array([[ 0.93028778,  0.29830605,  0.12335902],
       [-1.71762502,  0.20186231,  0.82181835],
       [ 1.30031955, -0.69478601, -0.57734811],
       [-0.38912785, -0.99026918, -0.65921485],
       [ 0.09098811,  1.31364357,  0.53493965],
       [-1.29801488,  1.38907993, -0.19194874],
       [ 0.64341587, -0.43238801, -2.78222275],
       [-0.05073601,  0.14748658, -0.76340914],
       [ 0.1119997 , -0.22133236,  0.66097254],
       [ 1.54091215, -0.13194016,  1.39128649]], dtype=float32)

tf.truncated_normal()은 tf.random_normal()과 동일하나, 표준편차의 2배를 넘어서는 값 (outlier) 은 배제한다는 점에서만 차이가 난다. (보다 몰린 값들이 나오게 된다)

In [45]:
b = tf.truncated_normal(shape=[10,3], mean=0, stddev=1.0, dtype=tf.float32)
b.eval() # outlier (-2 미만, 2 초과) 값은 존재하지 않는다.

array([[-0.40378946, -1.04522908, -0.60367399],
       [-1.16162038, -0.65031695, -0.40020686],
       [-0.11500889, -0.26668152,  0.04833195],
       [ 0.29022643,  0.0457669 ,  0.99933207],
       [ 0.0548622 , -0.37452129, -0.92584282],
       [ 0.89348567,  0.31437814, -1.14617348],
       [ 0.52522844, -0.48945293,  0.24500895],
       [-1.21908176,  0.05064929, -1.19746184],
       [ 0.46640307,  1.71970093, -0.09286413],
       [-0.91502059,  0.5404036 ,  0.1535054 ]], dtype=float32)

특정 범위 내의 랜덤한 값을 생성하려면 tf.random_uniform()을 사용한다

In [46]:
c = tf.random_uniform(shape=[2,3], minval=0, maxval=3, dtype=tf.float32)
c.eval()

array([[ 2.67031431,  1.44947541,  0.38993418],
       [ 0.5961535 ,  1.56822109,  2.72638655]], dtype=float32)

랜덤하게 shuffle해 주려면 tf.random_shuffle()을 사용한다. shuffle 기준은 1차원 (행) 이다.

In [48]:
d = tf.constant([[2,1], [2,2], [3,5]])
tf.random_shuffle(d).eval()

array([[3, 5],
       [2, 1],
       [2, 2]], dtype=int32)

tf.multinomial()은 주사위 연산과 같은 다항분포 연산이다.

In [49]:
# 5보다 작은 값 (0~4) 이 4 x 10 으로 생성된다.
e = tf.random_normal(shape=[4,5])
f = tf.multinomial(e, num_samples=10)
f.eval()

array([[0, 0, 4, 4, 0, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 4, 4, 4, 4, 0],
       [1, 4, 0, 2, 0, 2, 2, 1, 1, 1],
       [4, 0, 3, 4, 2, 3, 4, 3, 3, 4]])

In [50]:
# 10보다 작은 값 (0~9) 이 1 x 5 로 생성된다.
g = tf.random_normal(shape=[1,10])
h = tf.multinomial(g, num_samples=5)
h.eval()

array([[2, 0, 4, 9, 3]])

tf.random_gamma()도 있다. (의미는 잘 모르겠음)

In [51]:
tf.random_gamma([10],5).eval()

array([ 3.62039375,  4.34878016,  7.6895256 ,  6.34946156,  7.0542016 ,
        5.92448664,  6.2523303 ,  3.8250258 ,  4.44606733,  4.58176565], dtype=float32)

In [52]:
tf.random_gamma([10], [5,15]).eval()

array([[  6.85237646,  17.70995522],
       [  2.17907047,  13.38033104],
       [  3.922436  ,  13.7982111 ],
       [  5.69835711,  10.34441471],
       [  2.52006531,  17.91058159],
       [  3.91632342,  10.49040031],
       [ 16.98633575,  15.15886879],
       [  7.29740572,  15.18103218],
       [  8.7530899 ,  22.66994286],
       [  3.28235579,  16.33962059]], dtype=float32)

### Random 에 seed 주기

실행할 때마다 랜덤 값을 같게 해 주려면 seed를 이용합니다. 이때 Seed에는 두가지 종류가 있습니다.
* Graph-level seed
    * tf.set_random_seed(seed) 로 생성
* Operation-level seed
    * tf.random_normal(shape, mean, stddev, dtype, seed=1) 식으로 operation에 지정

그러므로 Seed 설정에는 총 4가지 경우의 수가 있습니다. 

* Graph-level seed와 operation-level seed가 모두 설정되지 않은 경우
    * 그냥 랜덤하게 seed가 설정됩니다.
* Graph-level seed가 설정되고 operation-level seed가 설정되지 않은 경우
    * Graph-level seed 설정 값을 따르며 유니크한 랜덤 시퀀스를 보이게 됩니다.
* Graph-level seed가 설정되지 않고 operation-level seed만 설정된 경우
    * 디폴트 graph-level seed와 지정된 operation-level seed가 사용됩니다.
* Graph-level seed와 operation-level seed 모두 설정된 경우
    * 2개 seed가 모두 사용됩니다.

우선 그냥 모든 세션에 대해 랜덤하게 다른 시퀀스를 출력하게 하려면 글로벌 시드와 오퍼레이션 시드 모두를 설정하지 않으면 됩니다.

In [54]:
a = tf.random_uniform([1])
b = tf.random_normal([1])

print("Session 1")
with tf.Session() as sess1:
  print(sess1.run(a))  # generates 'A1'
  print(sess1.run(a))  # generates 'A2'
  print(sess1.run(b))  # generates 'B1'
  print(sess1.run(b))  # generates 'B2'

print("Session 2")
with tf.Session() as sess2:
  print(sess2.run(a))  # generates 'A3'
  print(sess2.run(a))  # generates 'A4'
  print(sess2.run(b))  # generates 'B3'
  print(sess2.run(b))  # generates 'B4'

Session 1
[ 0.01633406]
[ 0.56579006]
[ 0.46902475]
[-0.08247837]
Session 2
[ 0.58892441]
[ 0.74401021]
[ 0.8889696]
[-0.816939]


세션마다 op에 대해 같은 순서로 반복되는 시퀀스를 만들고 싶으면 op에 seed를 설정합니다.

In [55]:
a = tf.random_uniform([1], seed=1)
b = tf.random_normal([1])

# Repeatedly running this block with the same graph will generate the same
# sequence of values for 'a', but different sequences of values for 'b'.
print("Session 1")
with tf.Session() as sess1:
  print(sess1.run(a))  # generates 'A1'
  print(sess1.run(a))  # generates 'A2'
  print(sess1.run(b))  # generates 'B1'
  print(sess1.run(b))  # generates 'B2'

print("Session 2")
with tf.Session() as sess2:
  print(sess2.run(a))  # generates 'A1'
  print(sess2.run(a))  # generates 'A2'
  print(sess2.run(b))  # generates 'B3'
  print(sess2.run(b))  # generates 'B4'

Session 1
[ 0.23903739]
[ 0.22267115]
[-0.46482995]
[-0.42111719]
Session 2
[ 0.23903739]
[ 0.22267115]
[-1.26221621]
[ 0.68382245]


세션들에 있어 모든 op에 대해 같은 순서로 반복되는 시퀀스를 만드려면 graph-level seed를 설정합니다.

In [56]:
tf.set_random_seed(1234)
a = tf.random_uniform([1])
b = tf.random_normal([1])

# Repeatedly running this block with the same graph will generate the same
# sequences of 'a' and 'b'.
print("Session 1")
with tf.Session() as sess1:
  print(sess1.run(a))  # generates 'A1'
  print(sess1.run(a))  # generates 'A2'
  print(sess1.run(b))  # generates 'B1'
  print(sess1.run(b))  # generates 'B2'

print("Session 2")
with tf.Session() as sess2:
  print(sess2.run(a))  # generates 'A1'
  print(sess2.run(a))  # generates 'A2'
  print(sess2.run(b))  # generates 'B1'
  print(sess2.run(b))  # generates 'B2'

Session 1
[ 0.15202892]
[ 0.28842747]
[-0.93776786]
[ 1.12402499]
Session 2
[ 0.15202892]
[ 0.28842747]
[-0.93776786]
[ 1.12402499]
