In [1]:
import tensorflow as tf

# Data Types

* boolean
* int
* float
* string

In [2]:
tf.InteractiveSession()

### 0D tensor = scalar

In [4]:
t_0 = 19
tf.zeros_like(t_0).eval()

0

In [5]:
tf.ones_like(t_0).eval()

1

### 1D tensor = vector

In [8]:
t_1 = ['apple', 'peach', 'banana']
tf.zeros_like(t_1).eval() # 문자열인 경우 빈 문자열로 변환된다!

array(['', '', ''], dtype=object)

In [9]:
# tf.ones_like(t_1).eval() # error : Expected string, got 1 of type 'int' instead.

### 2D tensor = matrix

In [12]:
t_2 = [[True, False, False],
       [False, False, True],
       [False, True, False]]
tf.zeros_like(t_2).eval() # boolean의 경우 모두 False로 변환된다!

array([[False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [14]:
tf.ones_like(t_2).eval() # boolean의 경우 모두 True로 변환된다!

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

### Data types in TF vs. NP

TF는 numpy와 seamlessly 통합될 수 있습니다

In [19]:
import numpy as np
tf.int32 == np.int32 # True

True

In [21]:
tf.ones([2,2], np.float32).eval() # numpy type 전달 가능!

array([[ 1.,  1.],
       [ 1.,  1.]], dtype=float32)

이처럼 텐서에 대해 numpy는 사용해도 무방하나, 파이썬의 type은 사용하지 않는게 좋다. 텐서플로우가 파이썬 type이 뭔지 infer해야 하므로 효율성이 떨어지기 때문이다. 물론 Tensorflow와 Numpy의 호환성이 언제까지 유지된다는 보장은 없기 때문에 유의해야 할 것이다.

### 상수의 문제점

상수는 그래프 정의 내에 저장되게 된다. 그러므로 상수가 큰 경우에는 그래프의 로딩이 비싸지게 된다.
* 따라서 primitive type에 대해서만 상수를 이용해라
* 보다 많은 메모리를 필요로 하는 데이터에 대해서는 변수 또는 reader를 사용해라!

그래프가 어떻게 정의되어 있는지 보도록 하겠습니다. 이때 사용하는 것이 sess.graph.as_graph_def() 입니다. 

In [22]:
my_const = tf.constant([1.0,2.0], name='my_const')
with tf.Session() as sess:
    print sess.graph.as_graph_def()

node {
  name: "zeros_like/tensor"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 19
      }
    }
  }
}
node {
  name: "zeros_like"
  op: "ZerosLike"
  input: "zeros_like/tensor"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "ones_like/tensor"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 19
      }
    }
  }
}
node {
  name: "ones_like/Shape"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
          }
        }
      }
    }
  }
}
node {
  name: "ones_like/Const"
  op: "Const"
  

### 상수 vs. 변수 vs. Placeholder

사실 상수는 그래프에 바로 올라가는데, 많이 사용되지 않는다.
반면 대부분 사용되는 것은 변수와 placeholder로, 그래프에 바로 올라가지 않는다.